id = "aylin-theme"
name = "Aylin Theme"
version = "0.6.0"
schema_version = 1
authors = ["blaqat <blaqat.ag@gmail.com>"]
description = "A port of a port of Aylin: a modern and minimal dark theme with bright colors for Zed"
repository = "https://github.com/biaqat/aylin-theme-zed"
