id = "aylin-theme"
name = "Aylin Theme"
version = "0.5.0"
schema_version = 1
authors = ["blaqat <blaqat.ag@gmail.com>"]
description = "Aylin theme for Zed"
repository = "https://github.com/biaqat/aylin-theme-zed"